// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by huatuo-openapi-errorcodes. DO NOT EDIT.

package v1

// HTTPStatusForErrorCode returns the default request-level HTTP status.
func HTTPStatusForErrorCode(code ErrorCode) (int, bool) {
	switch code {
	case ErrorCodeInternal:
		return 500, true
	case ErrorCodeInvalidRequest:
		return 400, true
	case ErrorCodeMethodNotAllowed:
		return 405, true
	case ErrorCodePermissionDenied:
		return 403, true
	case ErrorCodeRequestTooLarge:
		return 413, true
	case ErrorCodeRouteNotFound:
		return 404, true
	case ErrorCodeServiceUnavailable:
		return 503, true
	case ErrorCodeUnauthenticated:
		return 401, true
	case ErrorCodeUnsupportedMediaType:
		return 415, true
	default:
		return 0, false
	}
}
