// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package v1 provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package v1

// Defines values for ObservationScope.
const (
	ObservationScopeContainer ObservationScope = "container"
	ObservationScopeHost      ObservationScope = "host"
)

// Valid indicates whether the value is a known member of the ObservationScope enum.
func (e ObservationScope) Valid() bool {
	switch e {
	case ObservationScopeContainer:
		return true
	case ObservationScopeHost:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable error code.
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// ObservationScope Boundary observed by an on-demand operation.
type ObservationScope string

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string
