// Copyright 2025 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package tracing

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"math/big"
	"os/exec"
	"path"
	"sort"
	"sync"
	"time"

	"huatuo-bamai/internal/log"
)

// Status represents the status of a task.
type Status string

const (
	// StatusCompleted represents a task that has finished executing successfully.
	StatusCompleted = "completed"
	// StatusFailed represents a task that encountered an error during execution.
	StatusFailed = "failed"
	// StatusPending represents a task that has been created but has not yet begun execution.
	StatusPending = "pending"
	// StatusRunning represents a task that is currently being executed.
	StatusRunning = "running"
	// StatusNotExist represents a task that has either never been created or has been removed.
	StatusNotExist = "not_exist"
)

var TaskBinDir = "bin"

type TaskStorageType int

const (
	TaskStorageDB TaskStorageType = iota + 1
	TaskStorageStdout
	TaskStorageLocal
	TaskStorageDBJSON // JSON data
)

type TaskResult struct {
	TaskStatus Status
	TaskData   []byte
	TaskErr    error
}

// TaskInfo is a lightweight task summary returned by list APIs.
type TaskInfo struct {
	TaskID     string `json:"task_id"`
	TracerName string `json:"tracer_name"`
	Status     Status `json:"status"`
}

// task represents a unit of work to be executed.
type task struct {
	mu           sync.Mutex        // Protects status, error, stdoutData, deadlineTime
	id           string            // Unique identifier for the task.
	execBinary   string            // Path to the executable file to run for this task.
	execArgs     []string          // Arguments to pass to the executable.
	stdoutData   []byte            // Data generated by the task.
	status       Status            // Current status of the task.
	error        error             // Error encountered during task execution.
	storage      TaskStorageType   // Type of data produced by the task.
	cancelFunc   context.CancelFunc // Function to cancel the task.
	deadlineTime time.Time         // Time after which the task will be automatically deleted.
}

var (
	taskLifeTmpCache sync.Map
	// ErrTaskNotFound Error returned when a task is not found.
	ErrTaskNotFound = errors.New("task not found")
	// ErrTaskTimeout Error returned when a task times out.
	ErrTaskTimeout = errors.New("task timeout")
	// ErrTaskCanceled Error returned when a task is canceled.
	ErrTaskCanceled = errors.New("task canceled")
)

func init() {
	go tasksGarbageCollect()
}

func tasksGarbageCollect() {
	ticker := time.NewTicker(time.Second * 10)
	defer ticker.Stop()

	for range ticker.C {
		now := time.Now()
		taskLifeTmpCache.Range(func(key, value any) bool {
			task, ok := value.(*task)
			if !ok {
				return true
			}
			task.mu.Lock()
			status := task.status
			deadline := task.deadlineTime
			task.mu.Unlock()
			if status == StatusCompleted || status == StatusFailed {
				if now.After(deadline) {
					log.Infof("task %s deleted by timeout", key)
					taskLifeTmpCache.Delete(key)
				}
			}
			return true
		})
	}
}

// AllocTaskID returns a fresh random identifier suitable for tasks and tracer
// records. If the cryptographic random source fails, it logs the error and
// falls back to a timestamp-based identifier instead of panicking.
func AllocTaskID() string {
	const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	const length = 16
	result := make([]byte, length)
	charsetLength := big.NewInt(int64(len(charset)))

	for i := range result {
		num, err := rand.Int(rand.Reader, charsetLength)
		if err != nil {
			log.Errorf("crypto/rand failed in AllocTaskID: %v, using fallback", err)
			return fmt.Sprintf("fb%d", time.Now().UnixNano())
		}
		result[i] = charset[num.Int64()]
	}

	return string(result)
}

// NewTask creates a new task, allocates an ID, and starts it.
func NewTask(execBinary string, timeout time.Duration, storageType TaskStorageType, execArgs []string) string {
	taskID := AllocTaskID()
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	task := &task{
		id:         taskID,
		status:     StatusPending,
		cancelFunc: cancel,
		execBinary: execBinary,
		storage:    storageType,
		execArgs:   execArgs,
	}
	taskLifeTmpCache.Store(taskID, task)

	go runTask(ctx, task)

	return taskID
}

func runTask(ctx context.Context, task *task) {
	defer func() {
		setDeadlineDefault(task)
	}()

	task.mu.Lock()
	task.status = StatusRunning
	binaryName := task.execBinary
	taskID := task.id
	task.mu.Unlock()
	log.Infof("task %s %s started", binaryName, taskID)

	cmd := exec.CommandContext(ctx, path.Join(TaskBinDir, task.execBinary), task.execArgs...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		task.mu.Lock()
		task.status = StatusFailed
		contextErr := ctx.Err()
		if errors.Is(contextErr, context.DeadlineExceeded) {
			task.error = ErrTaskTimeout
		} else if errors.Is(contextErr, context.Canceled) {
			task.error = ErrTaskCanceled
		} else {
			task.error = fmt.Errorf("task error: %s| cmd error: %s", err.Error(), string(output))
		}
		errStr := task.error.Error()
		task.mu.Unlock()
		log.Infof("task %s %s failed: %s", binaryName, taskID, errStr)
		return
	}

	saveTaskOutputByType(task, time.Now(), output)

	task.mu.Lock()
	task.status = StatusCompleted
	task.mu.Unlock()
	log.Infof("task %s completed: %s", taskID, fmt.Sprint(binaryName, task.execArgs))
}

func saveTaskOutputByType(task *task, startAt time.Time, output []byte) {
	switch task.storage {
	case TaskStorageDB:
		if err := SaveTaskOutputText(&WriteRequest{
			TracerName: task.execBinary,
			TracerID:   task.id,
			TracerTime: startAt,
			TracerData: string(output),
		}); err != nil {
			log.Infof("save task output %s %s failed: %v", task.execBinary, task.id, err)
		}
	case TaskStorageDBJSON:
		if err := SaveTaskOutputJSON(&WriteRequest{
			TracerName: task.execBinary,
			TracerID:   task.id,
			TracerTime: startAt,
			TracerData: string(output),
		}); err != nil {
			log.Infof("save task json output %s %s failed: %v", task.execBinary, task.id, err)
		}
	case TaskStorageStdout:
		task.mu.Lock()
		task.stdoutData = append(task.stdoutData, output...)
		task.mu.Unlock()
	case TaskStorageLocal:
	default:
		log.Warn("data storage type not supported")
	}
}

func setDeadlineDefault(task *task) {
	task.mu.Lock()
	task.deadlineTime = time.Now().Add(10 * time.Minute)
	task.mu.Unlock()
}

// RunningTaskCount gets the number of running tasks.
func RunningTaskCount() int {
	count := 0
	taskLifeTmpCache.Range(func(key, value any) bool {
		task, ok := value.(*task)
		if !ok {
			return true
		}
		task.mu.Lock()
		if task.status == StatusRunning {
			count++
		}
		task.mu.Unlock()
		return true
	})
	return count
}

// ListTasks returns summaries for all tasks currently kept in memory.
func ListTasks() []TaskInfo {
	tasks := make([]TaskInfo, 0)
	taskLifeTmpCache.Range(func(key, value any) bool {
		task, ok := value.(*task)
		if !ok {
			return true
		}
		task.mu.Lock()
		taskID := task.id
		status := task.status
		binary := task.execBinary
		task.mu.Unlock()
		if taskID == "" {
			if keyID, ok := key.(string); ok {
				taskID = keyID
			}
		}
		tasks = append(tasks, TaskInfo{
			TaskID:     taskID,
			TracerName: binary,
			Status:     status,
		})
		return true
	})

	sort.Slice(tasks, func(i, j int) bool {
		return tasks[i].TaskID < tasks[j].TaskID
	})
	return tasks
}

// Result returns the result of a task given its ID.
func Result(taskID string) *TaskResult {
	taskInterface, ok := taskLifeTmpCache.Load(taskID)
	if !ok {
		return &TaskResult{
			TaskStatus: StatusNotExist,
			TaskErr:    ErrTaskNotFound,
		}
	}

	task, ok := taskInterface.(*task)
	if !ok {
		return &TaskResult{
			TaskStatus: StatusNotExist,
			TaskErr:    ErrTaskNotFound,
		}
	}

	task.mu.Lock()
	status := task.status
	if status == StatusFailed || status == StatusCompleted {
		setDeadlineDefault(task)
	}
	data := task.stdoutData
	taskErr := task.error
	task.mu.Unlock()

	return &TaskResult{
		TaskData:   data,
		TaskStatus: status,
		TaskErr:    taskErr,
	}
}

// StopTask stops a running task given its ID.
func StopTask(taskID string) error {
	taskAny, ok := taskLifeTmpCache.Load(taskID)
	if !ok {
		return ErrTaskNotFound
	}

	task, ok := taskAny.(*task)
	if !ok {
		return ErrTaskNotFound
	}

	task.mu.Lock()
	isRunning := task.status == StatusRunning
	cancel := task.cancelFunc
	taskIDVal := task.id
	task.mu.Unlock()

	if isRunning && cancel != nil {
		cancel()
	}
	taskLifeTmpCache.Delete(taskID)
	log.Infof("task %s stopped", taskIDVal)
	return nil
}