name: Bug 反馈
description: 当你在代码中发现了一个 Bug，导致应用崩溃或抛出异常，或者有一个组件存在问题，或者某些地方看起来不符合预期。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢对项目的支持与关注。
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过[现有的问题](https://github.com/ccfos/huatuo/issues)
          required: true
  - type: textarea
    attributes:
      label: 你的环境
      description: 请详细告诉我们你的环境，如内核版本、架构、操作系统、HUATUO的commit-id等
      placeholder: |
        内核版本：...
        OS 发行版：...
        HUATUO commit-id：...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题，如涉及代码，可提供一个最小代码示例，并使用反引号```附上它
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 修复建议或方案
      description: 请详细告诉我们可能的修复办法，如涉及代码，可提供一个最小代码示例，并使用反引号```附上它
      placeholder: |
        你的修复建议或方案 ...
    validations:
      required: false
  - type: textarea
    attributes:
      label: 其他
      description: 其他描述，如涉及代码，可提供一个最小代码示例，并使用反引号```附上它
      placeholder: |
        其他 ...
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: 版本
      description: 你当前正在使用HUATUO的哪个版本/分支？
      options:
        - 1.0.0 (默认)
        - 1.0.1 (最新)
    validations:
      required: false
