name: 其他问题
description: 你的其他issues
title: "[others]: "
labels: ["others"]
body:
  - type: textarea
    attributes:
      label: 你的问题
      description: 清晰并简洁地描述你的问题。
    validations:
      required: true
