// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by huatuo-openapi-errorcodes. DO NOT EDIT.

package node

import apiv1 "huatuo-bamai/apis/v1"

const (
	ErrorCodeContainerNotFound               apiv1.ErrorCode = "container_not_found"
	ErrorCodeEventStreamLimitExceeded        apiv1.ErrorCode = "event_stream_limit_exceeded"
	ErrorCodeExecutionEnvironmentUnsupported apiv1.ErrorCode = "execution_environment_unsupported"
	ErrorCodeExecutionFailed                 apiv1.ErrorCode = "execution_failed"
	ErrorCodeExecutionStartFailed            apiv1.ErrorCode = "execution_start_failed"
	ErrorCodeExecutionStopFailed             apiv1.ErrorCode = "execution_stop_failed"
	ErrorCodeFinalizationFailed              apiv1.ErrorCode = "finalization_failed"
	ErrorCodeFinalizationTimeout             apiv1.ErrorCode = "finalization_timeout"
	ErrorCodeLaunchTimeout                   apiv1.ErrorCode = "launch_timeout"
	ErrorCodeOperationLimitExceeded          apiv1.ErrorCode = "operation_limit_exceeded"
	ErrorCodeOperationNotFound               apiv1.ErrorCode = "operation_not_found"
	ErrorCodeRequestIDConflict               apiv1.ErrorCode = "request_id_conflict"
	ErrorCodeServiceNotImplemented           apiv1.ErrorCode = "service_not_implemented"
)
