// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by huatuo-openapi-errorcodes. DO NOT EDIT.

package node

import apiv1 "huatuo-bamai/apis/v1"

// HTTPStatusForErrorCode returns the default request-level HTTP status.
func HTTPStatusForErrorCode(code apiv1.ErrorCode) (int, bool) {
	if status, ok := apiv1.HTTPStatusForErrorCode(code); ok {
		return status, true
	}

	switch code {
	case ErrorCodeContainerNotFound:
		return 404, true
	case ErrorCodeEventStreamLimitExceeded:
		return 429, true
	case ErrorCodeExecutionEnvironmentUnsupported:
		return 422, true
	case ErrorCodeExecutionFailed:
		return 500, true
	case ErrorCodeExecutionStartFailed:
		return 500, true
	case ErrorCodeExecutionStopFailed:
		return 500, true
	case ErrorCodeFinalizationFailed:
		return 500, true
	case ErrorCodeFinalizationTimeout:
		return 500, true
	case ErrorCodeLaunchTimeout:
		return 500, true
	case ErrorCodeOperationLimitExceeded:
		return 429, true
	case ErrorCodeOperationNotFound:
		return 404, true
	case ErrorCodeRequestIDConflict:
		return 409, true
	case ErrorCodeServiceNotImplemented:
		return 501, true
	default:
		return 0, false
	}
}
