// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package node provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package node

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "huatuo-bamai/apis/v1"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the bundled Node Agent OpenAPI document.
	// (GET /openapi.json)
	GetOpenAPI(c *gin.Context)

	// (GET /readyz)
	GetReadiness(c *gin.Context)

	// (POST /v1/operations)
	StartOperation(c *gin.Context)

	// (GET /v1/operations/{request_id})
	GetOperation(c *gin.Context, requestID RequestID)

	// (POST /v1/operations/{request_id}/stop)
	StopOperation(c *gin.Context, requestID RequestID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetOpenAPI operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPI(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAPI(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// StartOperation operation middleware
func (siw *ServerInterfaceWrapper) StartOperation(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartOperation(c)
}

// GetOperation operation middleware
func (siw *ServerInterfaceWrapper) GetOperation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOperation(c, requestID)
}

// StopOperation operation middleware
func (siw *ServerInterfaceWrapper) StopOperation(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopOperation(c, requestID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPI)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
	router.POST(options.BaseURL+"/v1/operations", wrapper.StartOperation)
	router.GET(options.BaseURL+"/v1/operations/:request_id", wrapper.GetOperation)
	router.POST(options.BaseURL+"/v1/operations/:request_id/stop", wrapper.StopOperation)
}

type BadRequestJSONResponse externalRef0.ErrorResponse

type ConflictJSONResponse externalRef0.ErrorResponse

type ExecutionEnvironmentUnsupportedJSONResponse externalRef0.ErrorResponse

type InternalErrorJSONResponse externalRef0.ErrorResponse

type NotFoundJSONResponse externalRef0.ErrorResponse

type NotImplementedJSONResponse externalRef0.ErrorResponse

type RequestTooLargeJSONResponse externalRef0.ErrorResponse

type ServiceUnavailableJSONResponse externalRef0.ErrorResponse

type TooManyRequestsJSONResponse externalRef0.ErrorResponse

type UnauthenticatedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthenticatedJSONResponse struct {
	Body externalRef0.ErrorResponse

	Headers UnauthenticatedResponseHeaders
}

type UnsupportedMediaTypeJSONResponse externalRef0.ErrorResponse

type GetOpenAPIRequestObject struct {
}

type GetOpenAPIResponseObject interface {
	VisitGetOpenAPIResponse(w http.ResponseWriter) error
}

type GetOpenAPI200JSONResponse map[string]interface{}

func (response GetOpenAPI200JSONResponse) VisitGetOpenAPIResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type StartOperationRequestObject struct {
	Body *StartOperationJSONRequestBody
}

type StartOperationResponseObject interface {
	VisitStartOperationResponse(w http.ResponseWriter) error
}

type StartOperation200JSONResponse OperationResponse

func (response StartOperation200JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation202JSONResponse OperationResponse

func (response StartOperation202JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation400JSONResponse struct{ BadRequestJSONResponse }

func (response StartOperation400JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StartOperation401JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation409JSONResponse struct{ ConflictJSONResponse }

func (response StartOperation409JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation413JSONResponse struct{ RequestTooLargeJSONResponse }

func (response StartOperation413JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response StartOperation415JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation422JSONResponse struct {
	ExecutionEnvironmentUnsupportedJSONResponse
}

func (response StartOperation422JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response StartOperation429JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation500JSONResponse struct{ InternalErrorJSONResponse }

func (response StartOperation500JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation501JSONResponse struct{ NotImplementedJSONResponse }

func (response StartOperation501JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type StartOperation503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response StartOperation503JSONResponse) VisitStartOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type GetOperationResponseObject interface {
	VisitGetOperationResponse(w http.ResponseWriter) error
}

type GetOperation200JSONResponse OperationResponse

func (response GetOperation200JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetOperation401JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response GetOperation404JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperation500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetOperation500JSONResponse) VisitGetOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopOperationRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type StopOperationResponseObject interface {
	VisitStopOperationResponse(w http.ResponseWriter) error
}

type StopOperation200JSONResponse OperationResponse

func (response StopOperation200JSONResponse) VisitStopOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopOperation202JSONResponse OperationResponse

func (response StopOperation202JSONResponse) VisitStopOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StopOperation401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StopOperation401JSONResponse) VisitStopOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopOperation404JSONResponse struct{ NotFoundJSONResponse }

func (response StopOperation404JSONResponse) VisitStopOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopOperation500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopOperation500JSONResponse) VisitStopOperationResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Return the bundled Node Agent OpenAPI document.
	// (GET /openapi.json)
	GetOpenAPI(ctx context.Context, request GetOpenAPIRequestObject) (GetOpenAPIResponseObject, error)

	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)

	// (POST /v1/operations)
	StartOperation(ctx context.Context, request StartOperationRequestObject) (StartOperationResponseObject, error)

	// (GET /v1/operations/{request_id})
	GetOperation(ctx context.Context, request GetOperationRequestObject) (GetOperationResponseObject, error)

	// (POST /v1/operations/{request_id}/stop)
	StopOperation(ctx context.Context, request StopOperationRequestObject) (StopOperationResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetOpenAPI operation middleware
func (sh *strictHandler) GetOpenAPI(ctx *gin.Context) {
	var request GetOpenAPIRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPI(ctx, request.(GetOpenAPIRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPI")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetOpenAPIResponseObject); ok {
		if err := validResponse.VisitGetOpenAPIResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx *gin.Context) {
	var request GetReadinessRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartOperation operation middleware
func (sh *strictHandler) StartOperation(ctx *gin.Context) {
	var request StartOperationRequestObject

	var body StartOperationJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartOperation(ctx, request.(StartOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartOperation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StartOperationResponseObject); ok {
		if err := validResponse.VisitStartOperationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperation operation middleware
func (sh *strictHandler) GetOperation(ctx *gin.Context, requestID RequestID) {
	var request GetOperationRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperation(ctx, request.(GetOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetOperationResponseObject); ok {
		if err := validResponse.VisitGetOperationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopOperation operation middleware
func (sh *strictHandler) StopOperation(ctx *gin.Context, requestID RequestID) {
	var request StopOperationRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StopOperation(ctx, request.(StopOperationRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopOperation")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StopOperationResponseObject); ok {
		if err := validResponse.VisitStopOperationResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
