// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package node provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package node

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "huatuo-bamai/apis/v1"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the bundled Node Agent OpenAPI document.
	// (GET /openapi.json)
	GetOpenAPI(c *gin.Context)

	// (GET /readyz)
	GetReadiness(c *gin.Context)

	// (POST /v1/profiling)
	StartProfiling(c *gin.Context)

	// (GET /v1/profiling/{request_id})
	GetProfiling(c *gin.Context, requestID RequestID)

	// (POST /v1/profiling/{request_id}/stop)
	StopProfiling(c *gin.Context, requestID RequestID)

	// (POST /v1/tracing)
	StartTracing(c *gin.Context)

	// (GET /v1/tracing/{request_id})
	GetTracing(c *gin.Context, requestID RequestID)

	// (POST /v1/tracing/{request_id}/stop)
	StopTracing(c *gin.Context, requestID RequestID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetOpenAPI operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPI(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAPI(c)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReadiness(c)
}

// StartProfiling operation middleware
func (siw *ServerInterfaceWrapper) StartProfiling(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartProfiling(c)
}

// GetProfiling operation middleware
func (siw *ServerInterfaceWrapper) GetProfiling(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfiling(c, requestID)
}

// StopProfiling operation middleware
func (siw *ServerInterfaceWrapper) StopProfiling(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopProfiling(c, requestID)
}

// StartTracing operation middleware
func (siw *ServerInterfaceWrapper) StartTracing(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StartTracing(c)
}

// GetTracing operation middleware
func (siw *ServerInterfaceWrapper) GetTracing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTracing(c, requestID)
}

// StopTracing operation middleware
func (siw *ServerInterfaceWrapper) StopTracing(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopTracing(c, requestID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPI)
	router.GET(options.BaseURL+"/readyz", wrapper.GetReadiness)
	router.POST(options.BaseURL+"/v1/profiling", wrapper.StartProfiling)
	router.GET(options.BaseURL+"/v1/profiling/:request_id", wrapper.GetProfiling)
	router.POST(options.BaseURL+"/v1/profiling/:request_id/stop", wrapper.StopProfiling)
	router.POST(options.BaseURL+"/v1/tracing", wrapper.StartTracing)
	router.GET(options.BaseURL+"/v1/tracing/:request_id", wrapper.GetTracing)
	router.POST(options.BaseURL+"/v1/tracing/:request_id/stop", wrapper.StopTracing)
}

type BadRequestJSONResponse externalRef0.ErrorResponse

type ConflictJSONResponse externalRef0.ErrorResponse

type ExecutionEnvironmentUnsupportedJSONResponse externalRef0.ErrorResponse

type InternalErrorJSONResponse externalRef0.ErrorResponse

type NotFoundJSONResponse externalRef0.ErrorResponse

type NotImplementedJSONResponse externalRef0.ErrorResponse

type RequestTooLargeJSONResponse externalRef0.ErrorResponse

type ServiceUnavailableJSONResponse externalRef0.ErrorResponse

type TooManyRequestsJSONResponse externalRef0.ErrorResponse

type UnauthenticatedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthenticatedJSONResponse struct {
	Body externalRef0.ErrorResponse

	Headers UnauthenticatedResponseHeaders
}

type UnsupportedMediaTypeJSONResponse externalRef0.ErrorResponse

type GetOpenAPIRequestObject struct {
}

type GetOpenAPIResponseObject interface {
	VisitGetOpenAPIResponse(w http.ResponseWriter) error
}

type GetOpenAPI200JSONResponse map[string]interface{}

func (response GetOpenAPI200JSONResponse) VisitGetOpenAPIResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadinessRequestObject struct {
}

type GetReadinessResponseObject interface {
	VisitGetReadinessResponse(w http.ResponseWriter) error
}

type GetReadiness204Response struct {
}

func (response GetReadiness204Response) VisitGetReadinessResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type StartProfilingRequestObject struct {
	Body *StartProfilingJSONRequestBody
}

type StartProfilingResponseObject interface {
	VisitStartProfilingResponse(w http.ResponseWriter) error
}

type StartProfiling200JSONResponse OperationResponse

func (response StartProfiling200JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling202JSONResponse OperationResponse

func (response StartProfiling202JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling400JSONResponse struct{ BadRequestJSONResponse }

func (response StartProfiling400JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StartProfiling401JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling409JSONResponse struct{ ConflictJSONResponse }

func (response StartProfiling409JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling413JSONResponse struct{ RequestTooLargeJSONResponse }

func (response StartProfiling413JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response StartProfiling415JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling422JSONResponse struct {
	ExecutionEnvironmentUnsupportedJSONResponse
}

func (response StartProfiling422JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response StartProfiling429JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling500JSONResponse struct{ InternalErrorJSONResponse }

func (response StartProfiling500JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartProfiling503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response StartProfiling503JSONResponse) VisitStartProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type GetProfilingResponseObject interface {
	VisitGetProfilingResponse(w http.ResponseWriter) error
}

type GetProfiling200JSONResponse OperationResponse

func (response GetProfiling200JSONResponse) VisitGetProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfiling401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetProfiling401JSONResponse) VisitGetProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfiling404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProfiling404JSONResponse) VisitGetProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfiling500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetProfiling500JSONResponse) VisitGetProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type StopProfilingResponseObject interface {
	VisitStopProfilingResponse(w http.ResponseWriter) error
}

type StopProfiling200JSONResponse OperationResponse

func (response StopProfiling200JSONResponse) VisitStopProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfiling202JSONResponse OperationResponse

func (response StopProfiling202JSONResponse) VisitStopProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfiling401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StopProfiling401JSONResponse) VisitStopProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfiling404JSONResponse struct{ NotFoundJSONResponse }

func (response StopProfiling404JSONResponse) VisitStopProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfiling500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopProfiling500JSONResponse) VisitStopProfilingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracingRequestObject struct {
	Body *StartTracingJSONRequestBody
}

type StartTracingResponseObject interface {
	VisitStartTracingResponse(w http.ResponseWriter) error
}

type StartTracing200JSONResponse OperationResponse

func (response StartTracing200JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing202JSONResponse OperationResponse

func (response StartTracing202JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing400JSONResponse struct{ BadRequestJSONResponse }

func (response StartTracing400JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StartTracing401JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing409JSONResponse struct{ ConflictJSONResponse }

func (response StartTracing409JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing413JSONResponse struct{ RequestTooLargeJSONResponse }

func (response StartTracing413JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response StartTracing415JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing422JSONResponse struct {
	ExecutionEnvironmentUnsupportedJSONResponse
}

func (response StartTracing422JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response StartTracing429JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing500JSONResponse struct{ InternalErrorJSONResponse }

func (response StartTracing500JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing501JSONResponse struct{ NotImplementedJSONResponse }

func (response StartTracing501JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(501)
	_, err := buf.WriteTo(w)
	return err
}

type StartTracing503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response StartTracing503JSONResponse) VisitStartTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type GetTracingResponseObject interface {
	VisitGetTracingResponse(w http.ResponseWriter) error
}

type GetTracing200JSONResponse OperationResponse

func (response GetTracing200JSONResponse) VisitGetTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracing401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetTracing401JSONResponse) VisitGetTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracing404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTracing404JSONResponse) VisitGetTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracing500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetTracing500JSONResponse) VisitGetTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type StopTracingResponseObject interface {
	VisitStopTracingResponse(w http.ResponseWriter) error
}

type StopTracing200JSONResponse OperationResponse

func (response StopTracing200JSONResponse) VisitStopTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracing202JSONResponse OperationResponse

func (response StopTracing202JSONResponse) VisitStopTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracing401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StopTracing401JSONResponse) VisitStopTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracing404JSONResponse struct{ NotFoundJSONResponse }

func (response StopTracing404JSONResponse) VisitStopTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracing500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopTracing500JSONResponse) VisitStopTracingResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Return the bundled Node Agent OpenAPI document.
	// (GET /openapi.json)
	GetOpenAPI(ctx context.Context, request GetOpenAPIRequestObject) (GetOpenAPIResponseObject, error)

	// (GET /readyz)
	GetReadiness(ctx context.Context, request GetReadinessRequestObject) (GetReadinessResponseObject, error)

	// (POST /v1/profiling)
	StartProfiling(ctx context.Context, request StartProfilingRequestObject) (StartProfilingResponseObject, error)

	// (GET /v1/profiling/{request_id})
	GetProfiling(ctx context.Context, request GetProfilingRequestObject) (GetProfilingResponseObject, error)

	// (POST /v1/profiling/{request_id}/stop)
	StopProfiling(ctx context.Context, request StopProfilingRequestObject) (StopProfilingResponseObject, error)

	// (POST /v1/tracing)
	StartTracing(ctx context.Context, request StartTracingRequestObject) (StartTracingResponseObject, error)

	// (GET /v1/tracing/{request_id})
	GetTracing(ctx context.Context, request GetTracingRequestObject) (GetTracingResponseObject, error)

	// (POST /v1/tracing/{request_id}/stop)
	StopTracing(ctx context.Context, request StopTracingRequestObject) (StopTracingResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetOpenAPI operation middleware
func (sh *strictHandler) GetOpenAPI(ctx *gin.Context) {
	var request GetOpenAPIRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPI(ctx, request.(GetOpenAPIRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPI")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetOpenAPIResponseObject); ok {
		if err := validResponse.VisitGetOpenAPIResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadiness operation middleware
func (sh *strictHandler) GetReadiness(ctx *gin.Context) {
	var request GetReadinessRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadiness(ctx, request.(GetReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReadinessResponseObject); ok {
		if err := validResponse.VisitGetReadinessResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartProfiling operation middleware
func (sh *strictHandler) StartProfiling(ctx *gin.Context) {
	var request StartProfilingRequestObject

	var body StartProfilingJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartProfiling(ctx, request.(StartProfilingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartProfiling")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StartProfilingResponseObject); ok {
		if err := validResponse.VisitStartProfilingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfiling operation middleware
func (sh *strictHandler) GetProfiling(ctx *gin.Context, requestID RequestID) {
	var request GetProfilingRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfiling(ctx, request.(GetProfilingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfiling")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProfilingResponseObject); ok {
		if err := validResponse.VisitGetProfilingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopProfiling operation middleware
func (sh *strictHandler) StopProfiling(ctx *gin.Context, requestID RequestID) {
	var request StopProfilingRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StopProfiling(ctx, request.(StopProfilingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopProfiling")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StopProfilingResponseObject); ok {
		if err := validResponse.VisitStopProfilingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StartTracing operation middleware
func (sh *strictHandler) StartTracing(ctx *gin.Context) {
	var request StartTracingRequestObject

	var body StartTracingJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartTracing(ctx, request.(StartTracingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartTracing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StartTracingResponseObject); ok {
		if err := validResponse.VisitStartTracingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTracing operation middleware
func (sh *strictHandler) GetTracing(ctx *gin.Context, requestID RequestID) {
	var request GetTracingRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTracing(ctx, request.(GetTracingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTracing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetTracingResponseObject); ok {
		if err := validResponse.VisitGetTracingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopTracing operation middleware
func (sh *strictHandler) StopTracing(ctx *gin.Context, requestID RequestID) {
	var request StopTracingRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StopTracing(ctx, request.(StopTracingRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopTracing")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StopTracingResponseObject); ok {
		if err := validResponse.VisitStopTracingResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
