// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package node provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package node

import (
	"time"

	externalRef0 "huatuo-bamai/apis/v1"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for OperationStatus.
const (
	OperationStatusCompleted OperationStatus = "completed"
	OperationStatusFailed    OperationStatus = "failed"
	OperationStatusPending   OperationStatus = "pending"
	OperationStatusRunning   OperationStatus = "running"
	OperationStatusStopped   OperationStatus = "stopped"
	OperationStatusStopping  OperationStatus = "stopping"
)

// Valid indicates whether the value is a known member of the OperationStatus enum.
func (e OperationStatus) Valid() bool {
	switch e {
	case OperationStatusCompleted:
		return true
	case OperationStatusFailed:
		return true
	case OperationStatusPending:
		return true
	case OperationStatusRunning:
		return true
	case OperationStatusStopped:
		return true
	case OperationStatusStopping:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingLanguage.
const (
	ProfilingLanguageC      ProfilingLanguage = "c"
	ProfilingLanguageCPP    ProfilingLanguage = "c++"
	ProfilingLanguageGo     ProfilingLanguage = "go"
	ProfilingLanguageJava   ProfilingLanguage = "java"
	ProfilingLanguagePython ProfilingLanguage = "python"
)

// Valid indicates whether the value is a known member of the ProfilingLanguage enum.
func (e ProfilingLanguage) Valid() bool {
	switch e {
	case ProfilingLanguageC:
		return true
	case ProfilingLanguageCPP:
		return true
	case ProfilingLanguageGo:
		return true
	case ProfilingLanguageJava:
		return true
	case ProfilingLanguagePython:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingMode.
const (
	ProfilingModeObjectAlloc   ProfilingMode = "object_alloc"
	ProfilingModeObjectUsage   ProfilingMode = "object_usage"
	ProfilingModeOffCPU        ProfilingMode = "offcpu"
	ProfilingModeOnCPU         ProfilingMode = "oncpu"
	ProfilingModePhysicalAlloc ProfilingMode = "physical_alloc"
	ProfilingModePhysicalUsage ProfilingMode = "physical_usage"
	ProfilingModeVirtualAlloc  ProfilingMode = "virtual_alloc"
)

// Valid indicates whether the value is a known member of the ProfilingMode enum.
func (e ProfilingMode) Valid() bool {
	switch e {
	case ProfilingModeObjectAlloc:
		return true
	case ProfilingModeObjectUsage:
		return true
	case ProfilingModeOffCPU:
		return true
	case ProfilingModeOnCPU:
		return true
	case ProfilingModePhysicalAlloc:
		return true
	case ProfilingModePhysicalUsage:
		return true
	case ProfilingModeVirtualAlloc:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingType.
const (
	ProfilingTypeCPU    ProfilingType = "cpu"
	ProfilingTypeMemory ProfilingType = "memory"
)

// Valid indicates whether the value is a known member of the ProfilingType enum.
func (e ProfilingType) Valid() bool {
	switch e {
	case ProfilingTypeCPU:
		return true
	case ProfilingTypeMemory:
		return true
	default:
		return false
	}
}

// Defines values for TracingType.
const (
	TracingTypeIO             TracingType = "io_tracing"
	TracingTypeNetworkingDrop TracingType = "networking_drop"
	TracingTypeTCPRetransmit  TracingType = "tcp_retransmit"
)

// Valid indicates whether the value is a known member of the TracingType enum.
func (e TracingType) Valid() bool {
	switch e {
	case TracingTypeIO:
		return true
	case TracingTypeNetworkingDrop:
		return true
	case TracingTypeTCPRetransmit:
		return true
	default:
		return false
	}
}

// Operation defines model for Operation.
type Operation struct {
	CreatedAt  time.Time         `json:"created_at"`
	Failure    *OperationFailure `json:"failure,omitempty"`
	FinishedAt *time.Time        `json:"finished_at,omitempty"`
	RequestID  string            `json:"request_id"`
	StartedAt  *time.Time        `json:"started_at,omitempty"`
	Status     OperationStatus   `json:"status"`
}

// OperationFailure defines model for OperationFailure.
type OperationFailure struct {
	// Code Stable machine-readable error code.
	Code    externalRef0.ErrorCode `json:"code"`
	Message string                 `json:"message"`
}

// OperationResponse defines model for OperationResponse.
type OperationResponse struct {
	Data Operation `json:"data"`
}

// OperationStatus defines model for OperationStatus.
type OperationStatus string

// ProfilingLanguage defines model for ProfilingLanguage.
type ProfilingLanguage string

// ProfilingMode defines model for ProfilingMode.
type ProfilingMode string

// ProfilingType defines model for ProfilingType.
type ProfilingType string

// StartProfilingRequest defines model for StartProfilingRequest.
type StartProfilingRequest struct {
	BinaryMatchPath *string           `json:"binary_match_path,omitempty"`
	ContainerID     *string           `json:"container_id,omitempty"`
	DurationSeconds int64             `json:"duration_seconds"`
	Language        ProfilingLanguage `json:"language"`
	Mode            ProfilingMode     `json:"mode"`
	RequestID       string            `json:"request_id"`

	// Scope Boundary observed by an on-demand operation.
	Scope externalRef0.ObservationScope `json:"scope"`
	Type  ProfilingType                 `json:"type"`
}

// StartTracingRequest defines model for StartTracingRequest.
type StartTracingRequest struct {
	ContainerID     *string `json:"container_id,omitempty"`
	DurationSeconds int64   `json:"duration_seconds"`
	RequestID       string  `json:"request_id"`

	// Scope Boundary observed by an on-demand operation.
	Scope externalRef0.ObservationScope `json:"scope"`
	Type  TracingType                   `json:"type"`
}

// TracingType defines model for TracingType.
type TracingType string

// RequestID defines model for RequestID.
type RequestID = string

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.ErrorResponse

// Conflict defines model for Conflict.
type Conflict = externalRef0.ErrorResponse

// ExecutionEnvironmentUnsupported defines model for ExecutionEnvironmentUnsupported.
type ExecutionEnvironmentUnsupported = externalRef0.ErrorResponse

// InternalError defines model for InternalError.
type InternalError = externalRef0.ErrorResponse

// NotFound defines model for NotFound.
type NotFound = externalRef0.ErrorResponse

// NotImplemented defines model for NotImplemented.
type NotImplemented = externalRef0.ErrorResponse

// RequestTooLarge defines model for RequestTooLarge.
type RequestTooLarge = externalRef0.ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = externalRef0.ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = externalRef0.ErrorResponse

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = externalRef0.ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = externalRef0.ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// StartProfilingJSONRequestBody defines body for StartProfiling for application/json ContentType.
type StartProfilingJSONRequestBody = StartProfilingRequest

// StartTracingJSONRequestBody defines body for StartTracing for application/json ContentType.
type StartTracingJSONRequestBody = StartTracingRequest
