// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package node provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package node

import (
	"encoding/json"
	"time"

	externalRef0 "huatuo-bamai/apis/v1"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for OperationKind.
const (
	OperationKindProfiling OperationKind = "profiling"
	OperationKindTracing   OperationKind = "tracing"
)

// Valid indicates whether the value is a known member of the OperationKind enum.
func (e OperationKind) Valid() bool {
	switch e {
	case OperationKindProfiling:
		return true
	case OperationKindTracing:
		return true
	default:
		return false
	}
}

// Defines values for OperationOutcome.
const (
	OperationOutcomeCompleted OperationOutcome = "completed"
	OperationOutcomeFailed    OperationOutcome = "failed"
	OperationOutcomeStopped   OperationOutcome = "stopped"
)

// Valid indicates whether the value is a known member of the OperationOutcome enum.
func (e OperationOutcome) Valid() bool {
	switch e {
	case OperationOutcomeCompleted:
		return true
	case OperationOutcomeFailed:
		return true
	case OperationOutcomeStopped:
		return true
	default:
		return false
	}
}

// Defines values for OperationStatus.
const (
	OperationStatusPending  OperationStatus = "pending"
	OperationStatusRunning  OperationStatus = "running"
	OperationStatusStopping OperationStatus = "stopping"
	OperationStatusTerminal OperationStatus = "terminal"
)

// Valid indicates whether the value is a known member of the OperationStatus enum.
func (e OperationStatus) Valid() bool {
	switch e {
	case OperationStatusPending:
		return true
	case OperationStatusRunning:
		return true
	case OperationStatusStopping:
		return true
	case OperationStatusTerminal:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingLanguage.
const (
	ProfilingLanguageC      ProfilingLanguage = "c"
	ProfilingLanguageCPP    ProfilingLanguage = "c++"
	ProfilingLanguageGo     ProfilingLanguage = "go"
	ProfilingLanguageJava   ProfilingLanguage = "java"
	ProfilingLanguagePython ProfilingLanguage = "python"
)

// Valid indicates whether the value is a known member of the ProfilingLanguage enum.
func (e ProfilingLanguage) Valid() bool {
	switch e {
	case ProfilingLanguageC:
		return true
	case ProfilingLanguageCPP:
		return true
	case ProfilingLanguageGo:
		return true
	case ProfilingLanguageJava:
		return true
	case ProfilingLanguagePython:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingMode.
const (
	ProfilingModeObjectAlloc   ProfilingMode = "object_alloc"
	ProfilingModeObjectUsage   ProfilingMode = "object_usage"
	ProfilingModeOffCPU        ProfilingMode = "offcpu"
	ProfilingModeOnCPU         ProfilingMode = "oncpu"
	ProfilingModePhysicalAlloc ProfilingMode = "physical_alloc"
	ProfilingModePhysicalUsage ProfilingMode = "physical_usage"
	ProfilingModeVirtualAlloc  ProfilingMode = "virtual_alloc"
)

// Valid indicates whether the value is a known member of the ProfilingMode enum.
func (e ProfilingMode) Valid() bool {
	switch e {
	case ProfilingModeObjectAlloc:
		return true
	case ProfilingModeObjectUsage:
		return true
	case ProfilingModeOffCPU:
		return true
	case ProfilingModeOnCPU:
		return true
	case ProfilingModePhysicalAlloc:
		return true
	case ProfilingModePhysicalUsage:
		return true
	case ProfilingModeVirtualAlloc:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingType.
const (
	ProfilingTypeCPU    ProfilingType = "cpu"
	ProfilingTypeMemory ProfilingType = "memory"
)

// Valid indicates whether the value is a known member of the ProfilingType enum.
func (e ProfilingType) Valid() bool {
	switch e {
	case ProfilingTypeCPU:
		return true
	case ProfilingTypeMemory:
		return true
	default:
		return false
	}
}

// Defines values for TracingType.
const (
	TracingTypeIO             TracingType = "io_tracing"
	TracingTypeNetworkingDrop TracingType = "networking_drop"
	TracingTypeTCPRetransmit  TracingType = "tcp_retransmit"
)

// Valid indicates whether the value is a known member of the TracingType enum.
func (e TracingType) Valid() bool {
	switch e {
	case TracingTypeIO:
		return true
	case TracingTypeNetworkingDrop:
		return true
	case TracingTypeTCPRetransmit:
		return true
	default:
		return false
	}
}

// ContainerMetadata defines model for ContainerMetadata.
type ContainerMetadata struct {
	CgroupCSS map[string]string `json:"cgroup_css"`
	ID        string            `json:"id"`
}

// ContainerResponse defines model for ContainerResponse.
type ContainerResponse struct {
	Data ContainerMetadata `json:"data"`
}

// Operation defines model for Operation.
type Operation struct {
	CreatedAt  time.Time          `json:"created_at"`
	FinishedAt *time.Time         `json:"finished_at,omitempty"`
	Kind       OperationKind      `json:"kind"`
	RequestID  string             `json:"request_id"`
	StartedAt  *time.Time         `json:"started_at,omitempty"`
	Status     OperationStatus    `json:"status"`
	Terminal   *OperationTerminal `json:"terminal,omitempty"`
}

// OperationKind defines model for OperationKind.
type OperationKind string

// OperationOutcome defines model for OperationOutcome.
type OperationOutcome string

// OperationResponse defines model for OperationResponse.
type OperationResponse struct {
	Data Operation `json:"data"`
}

// OperationStatus defines model for OperationStatus.
type OperationStatus string

// OperationTerminal defines model for OperationTerminal.
type OperationTerminal struct {
	Message *string          `json:"message,omitempty"`
	Outcome OperationOutcome `json:"outcome"`
	Reason  *string          `json:"reason,omitempty"`
}

// ProfilingLanguage defines model for ProfilingLanguage.
type ProfilingLanguage string

// ProfilingMode defines model for ProfilingMode.
type ProfilingMode string

// ProfilingOperationSpec defines model for ProfilingOperationSpec.
type ProfilingOperationSpec struct {
	BinaryMatchPath *string           `json:"binary_match_path,omitempty"`
	Language        ProfilingLanguage `json:"language"`
	Mode            ProfilingMode     `json:"mode"`
	Type            ProfilingType     `json:"type"`
}

// ProfilingType defines model for ProfilingType.
type ProfilingType string

// StartOperationRequest defines model for StartOperationRequest.
type StartOperationRequest struct {
	ContainerID     *string       `json:"container_id,omitempty"`
	DurationSeconds int64         `json:"duration_seconds"`
	Kind            OperationKind `json:"kind"`
	RequestID       string        `json:"request_id"`

	// Scope Boundary observed by an on-demand operation.
	Scope externalRef0.ObservationScope `json:"scope"`
	Spec  StartOperationRequest_Spec    `json:"spec"`
}

// StartOperationRequest_Spec defines model for StartOperationRequest.Spec.
type StartOperationRequest_Spec struct {
	union json.RawMessage
}

// TracingOperationSpec defines model for TracingOperationSpec.
type TracingOperationSpec struct {
	Type TracingType `json:"type"`
}

// TracingType defines model for TracingType.
type TracingType string

// ContainerID defines model for ContainerID.
type ContainerID = string

// RequestID defines model for RequestID.
type RequestID = string

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.ErrorResponse

// Conflict defines model for Conflict.
type Conflict = externalRef0.ErrorResponse

// ContainerNotFound defines model for ContainerNotFound.
type ContainerNotFound = externalRef0.ErrorResponse

// ExecutionEnvironmentUnsupported defines model for ExecutionEnvironmentUnsupported.
type ExecutionEnvironmentUnsupported = externalRef0.ErrorResponse

// InternalError defines model for InternalError.
type InternalError = externalRef0.ErrorResponse

// NotFound defines model for NotFound.
type NotFound = externalRef0.ErrorResponse

// NotImplemented defines model for NotImplemented.
type NotImplemented = externalRef0.ErrorResponse

// RequestTooLarge defines model for RequestTooLarge.
type RequestTooLarge = externalRef0.ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = externalRef0.ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = externalRef0.ErrorResponse

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = externalRef0.ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = externalRef0.ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// StartOperationJSONRequestBody defines body for StartOperation for application/json ContentType.
type StartOperationJSONRequestBody = StartOperationRequest

// AsProfilingOperationSpec returns the union data inside the StartOperationRequest_Spec as a ProfilingOperationSpec
func (t StartOperationRequest_Spec) AsProfilingOperationSpec() (ProfilingOperationSpec, error) {
	var body ProfilingOperationSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProfilingOperationSpec overwrites any union data inside the StartOperationRequest_Spec as the provided ProfilingOperationSpec
func (t *StartOperationRequest_Spec) FromProfilingOperationSpec(v ProfilingOperationSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProfilingOperationSpec performs a merge with any union data inside the StartOperationRequest_Spec, using the provided ProfilingOperationSpec
func (t *StartOperationRequest_Spec) MergeProfilingOperationSpec(v ProfilingOperationSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTracingOperationSpec returns the union data inside the StartOperationRequest_Spec as a TracingOperationSpec
func (t StartOperationRequest_Spec) AsTracingOperationSpec() (TracingOperationSpec, error) {
	var body TracingOperationSpec
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTracingOperationSpec overwrites any union data inside the StartOperationRequest_Spec as the provided TracingOperationSpec
func (t *StartOperationRequest_Spec) FromTracingOperationSpec(v TracingOperationSpec) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTracingOperationSpec performs a merge with any union data inside the StartOperationRequest_Spec, using the provided TracingOperationSpec
func (t *StartOperationRequest_Spec) MergeTracingOperationSpec(v TracingOperationSpec) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StartOperationRequest_Spec) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StartOperationRequest_Spec) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
