// Code generated by capnpc-go. DO NOT EDIT.

package transport

import (
	strconv "strconv"

	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type ConnectRequest capnp.Struct

// ConnectRequest_TypeID is the unique identifier for the type ConnectRequest.
const ConnectRequest_TypeID = 0x8f2f493ff325eae4

func NewConnectRequest(s *capnp.Segment) (ConnectRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ConnectRequest(st), err
}

func NewRootConnectRequest(s *capnp.Segment) (ConnectRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ConnectRequest(st), err
}

func ReadRootConnectRequest(msg *capnp.Message) (ConnectRequest, error) {
	root, err := msg.Root()
	return ConnectRequest(root.Struct()), err
}

func (s ConnectRequest) String() string {
	str, _ := text.Marshal(0x8f2f493ff325eae4, capnp.Struct(s))
	return str
}

func (s ConnectRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ConnectRequest) DecodeFromPtr(p capnp.Ptr) ConnectRequest {
	return ConnectRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ConnectRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s ConnectRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ConnectRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ConnectRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s ConnectRequest) ToolName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ConnectRequest) HasToolName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ConnectRequest) ToolNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ConnectRequest) SetToolName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ConnectRequest) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ConnectRequest) HasVersion() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ConnectRequest) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ConnectRequest) SetVersion(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ConnectRequest) TaskID() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ConnectRequest) HasTaskID() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ConnectRequest) TaskIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ConnectRequest) SetTaskID(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ConnectRequest) ProtoVersion() uint32 {
	return capnp.Struct(s).Uint32(0) ^ 1
}

func (s ConnectRequest) SetProtoVersion(v uint32) {
	capnp.Struct(s).SetUint32(0, v^1)
}

// ConnectRequest_List is a list of ConnectRequest.
type ConnectRequest_List = capnp.StructList[ConnectRequest]

// NewConnectRequest_List creates a new list of ConnectRequest.
func NewConnectRequest_List(s *capnp.Segment, sz int32) (ConnectRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[ConnectRequest](l), err
}

// ConnectRequest_Future is a wrapper for a ConnectRequest promised by a client call.
type ConnectRequest_Future struct{ *capnp.Future }

func (f ConnectRequest_Future) Struct() (ConnectRequest, error) {
	p, err := f.Future.Ptr()
	return ConnectRequest(p.Struct()), err
}

type Chunk capnp.Struct

// Chunk_TypeID is the unique identifier for the type Chunk.
const Chunk_TypeID = 0xce30c8888d8869d3

func NewChunk(s *capnp.Segment) (Chunk, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Chunk(st), err
}

func NewRootChunk(s *capnp.Segment) (Chunk, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Chunk(st), err
}

func ReadRootChunk(msg *capnp.Message) (Chunk, error) {
	root, err := msg.Root()
	return Chunk(root.Struct()), err
}

func (s Chunk) String() string {
	str, _ := text.Marshal(0xce30c8888d8869d3, capnp.Struct(s))
	return str
}

func (s Chunk) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Chunk) DecodeFromPtr(p capnp.Ptr) Chunk {
	return Chunk(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Chunk) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Chunk) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Chunk) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Chunk) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Chunk) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Chunk) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Chunk) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Chunk) Flush() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Chunk) SetFlush(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Chunk) End() bool {
	return capnp.Struct(s).Bit(1)
}

func (s Chunk) SetEnd(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s Chunk) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Chunk) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Chunk) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Chunk) SetError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Chunk) ContainerID() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Chunk) HasContainerID() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Chunk) ContainerIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Chunk) SetContainerID(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// Chunk_List is a list of Chunk.
type Chunk_List = capnp.StructList[Chunk]

// NewChunk_List creates a new list of Chunk.
func NewChunk_List(s *capnp.Segment, sz int32) (Chunk_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Chunk](l), err
}

// Chunk_Future is a wrapper for a Chunk promised by a client call.
type Chunk_Future struct{ *capnp.Future }

func (f Chunk_Future) Struct() (Chunk, error) {
	p, err := f.Future.Ptr()
	return Chunk(p.Struct()), err
}

type (
	Message       capnp.Struct
	Message_Which uint16
)

const (
	Message_Which_connect Message_Which = 0
	Message_Which_chunk   Message_Which = 1
)

func (w Message_Which) String() string {
	const s = "connectchunk"
	switch w {
	case Message_Which_connect:
		return s[0:7]
	case Message_Which_chunk:
		return s[7:12]
	}
	return "Message_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0x8cfe5ee0d95f713d

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0x8cfe5ee0d95f713d, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Message) Which() Message_Which {
	return Message_Which(capnp.Struct(s).Uint16(0))
}

func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

func (s Message) Connect() (ConnectRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != connect")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ConnectRequest(p.Struct()), err
}

func (s Message) HasConnect() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message) SetConnect(v ConnectRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewConnect sets the connect field to a newly
// allocated ConnectRequest struct, preferring placement in s's segment.
func (s Message) NewConnect() (ConnectRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewConnectRequest(capnp.Struct(s).Segment())
	if err != nil {
		return ConnectRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message) Chunk() (Chunk, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != chunk")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return Chunk(p.Struct()), err
}

func (s Message) HasChunk() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message) SetChunk(v Chunk) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewChunk sets the chunk field to a newly
// allocated Chunk struct, preferring placement in s's segment.
func (s Message) NewChunk() (Chunk, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewChunk(capnp.Struct(s).Segment())
	if err != nil {
		return Chunk{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage_List creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}

func (p Message_Future) Connect() ConnectRequest_Future {
	return ConnectRequest_Future{Future: p.Future.Field(0, nil)}
}

func (p Message_Future) Chunk() Chunk_Future {
	return Chunk_Future{Future: p.Future.Field(0, nil)}
}

const schema_c0aefe4459d6cfa3 = "x\xdal\x90\xcbk\x13Q\x14\x87\x7f\xbfs\xa7N\x91" +
	"\x84f\xc8,\x95\xa0XP\xa1Z\x1f\xab\x82T\xb4." +
	"*(\x9e\x8d\xe0\xc2\xc78\xbd\x9a\x98\xf4N:\x99T" +
	"\x17-\xb5\xd0B\x84\x14\xc5\x95\xeb\xba\xf7op\xe9J" +
	"\x17\x82\xe0\xce\x85 \xb8u\x9f\x91IH\x83\x8f\xdd=" +
	"\x87\x0f\xbe\xef\xdc\xf9\xc3\xbc\xec\x9d+'\x02\xd1#S" +
	"\x87\xf2Kk\xf7\xbf~\xbb7\xe8CKd\xfe\xf6\xd3" +
	"\x97;K\x83w\xefq\x8d\xbe\x00\xd5\xa3\xdc\xaf\xce\xd2" +
	"\x07\xaa\xc7\xf8\x14\xcc\xbf\xff\x9c\xfd\xb5\xb8|\xf6\xe5_" +
	"\xf4\x94)\x90M\xeeWw\x87\xf06\x7f\x80\xf9\xe7F" +
	"o\xaf\xf7a\xfe\xe3\x7f\xe1\xbb\xf2\xbaj\xc5\x07.D" +
	"R#\xe6r\xbbn]v&\x8e\xd8v\xed\x85\x1b\xb6" +
	"\xd3\xf1\xa3\xc7\xf6\x16\xa9\xd3\xc6+\xe5\xb9G 8u" +
	"\x05\xd0\x13\x86:/,s\x90\x87,\xb6s\xe7\x01=" +
	"i\xa8\x17\x85[q\xe2\x9c\x8d3V&\xad +`" +
	"-\xaew]\x93\x95I\xd6h\xff\xa7\xf8j\xe2\x9co" +
	"\xe3\xac\x10W\x8c\x07\x0c\xbd\xd1u@\x1f\x18jK\x18" +
	"\x90#m\xa3\x88Y1\xd4\xb60\x10\x09)@\xb0\xba" +
	"\x00h\xddP3!MHC\x06kO\x00m\x1b\xea" +
	"\x860\xcf\x92\xa4u3Z\xb5\x00X\x82\xb0\x04n\xad" +
	"\xdb\xb4\xd3H\xdcx^\xcc\xa2Nsyi<\xe6\xed" +
	"4\xc9\x92\xdb6\xc5\xcc\x90\x9a\x86\x04\xd3\xfc'\xbc\xde" +
	"ul\x16\xd9\xe1A\xf6\xe6i@\x9f\x19\xea\x8ep\\" +
	"\xbd]|\xd6\x86\xa1\xf6\x8aj\x8e\xaaw\x8f\x03\xfa\xdc" +
	"P\xfb\xc2\xc00\xa4\x01\x82\x17\x05\xb9c\xa8\xaf\x84\x81" +
	"'!= \xd8{\x08h\xdfP\xdf\x08gV\xa2," +
	"b\x19\xc22X{\xd4\xeav\xea$\x84\x04}\xebV" +
	"\xc6\xef\x9aM\xd3$=\xb8&N\\\x165\x9c\x85\x9f" +
	"Nn\xfc\x1d\x00\x00\xff\xff\xf0\xb7\x95a"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c0aefe4459d6cfa3,
		Nodes: []uint64{
			0x8cfe5ee0d95f713d,
			0x8f2f493ff325eae4,
			0xce30c8888d8869d3,
		},
		Compressed: true,
	})
}
