// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by huatuo-openapi-errorcodes. DO NOT EDIT.

package server

import apiv1 "huatuo-bamai/apis/v1"

const (
	ErrorCodeExecutionCapacityExceeded apiv1.ErrorCode = "execution_capacity_exceeded"
	ErrorCodeExecutionFailed           apiv1.ErrorCode = "execution_failed"
	ErrorCodeExecutionStartFailed      apiv1.ErrorCode = "execution_start_failed"
	ErrorCodeExecutionTimedOut         apiv1.ErrorCode = "execution_timed_out"
	ErrorCodeJobConflict               apiv1.ErrorCode = "job_conflict"
	ErrorCodeJobNotFound               apiv1.ErrorCode = "job_not_found"
	ErrorCodeNodeUnavailable           apiv1.ErrorCode = "node_unavailable"
	ErrorCodeOperationLost             apiv1.ErrorCode = "operation_lost"
	ErrorCodeProtocolError             apiv1.ErrorCode = "protocol_error"
	ErrorCodeQuotaExceeded             apiv1.ErrorCode = "quota_exceeded"
	ErrorCodeResultNotReady            apiv1.ErrorCode = "result_not_ready"
	ErrorCodeResultUnavailable         apiv1.ErrorCode = "result_unavailable"
	ErrorCodeStartTimeout              apiv1.ErrorCode = "start_timeout"
	ErrorCodeStopTimeout               apiv1.ErrorCode = "stop_timeout"
)
