// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by huatuo-openapi-errorcodes. DO NOT EDIT.

package server

import apiv1 "huatuo-bamai/apis/v1"

// HTTPStatusForErrorCode returns the default request-level HTTP status.
func HTTPStatusForErrorCode(code apiv1.ErrorCode) (int, bool) {
	if status, ok := apiv1.HTTPStatusForErrorCode(code); ok {
		return status, true
	}

	switch code {
	case ErrorCodeExecutionCapacityExceeded:
		return 429, true
	case ErrorCodeExecutionFailed:
		return 500, true
	case ErrorCodeExecutionStartFailed:
		return 500, true
	case ErrorCodeExecutionTimedOut:
		return 500, true
	case ErrorCodeJobConflict:
		return 409, true
	case ErrorCodeJobNotFound:
		return 404, true
	case ErrorCodeNodeUnavailable:
		return 503, true
	case ErrorCodeOperationLost:
		return 500, true
	case ErrorCodeProtocolError:
		return 502, true
	case ErrorCodeQuotaExceeded:
		return 429, true
	case ErrorCodeResultNotFound:
		return 404, true
	case ErrorCodeResultNotReady:
		return 409, true
	case ErrorCodeResultUnavailable:
		return 409, true
	case ErrorCodeStartTimeout:
		return 500, true
	case ErrorCodeStopTimeout:
		return 500, true
	default:
		return 0, false
	}
}
