// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package server provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	externalRef0 "huatuo-bamai/apis/v1"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return the bundled Apiserver OpenAPI document.
	// (GET /openapi.json)
	GetOpenAPI(c *gin.Context)

	// (GET /v1/profiling)
	ListProfilingJobs(c *gin.Context, params ListProfilingJobsParams)

	// (POST /v1/profiling)
	CreateProfilingJob(c *gin.Context)

	// (GET /v1/profiling/capabilities)
	GetProfilingCapabilities(c *gin.Context)

	// (GET /v1/profiling/{request_id})
	GetProfilingJob(c *gin.Context, requestID RequestID)

	// (GET /v1/profiling/{request_id}/raw)
	GetRawProfiles(c *gin.Context, requestID RequestID, params GetRawProfilesParams)

	// (POST /v1/profiling/{request_id}/stop)
	StopProfilingJob(c *gin.Context, requestID RequestID)

	// (GET /v1/tracing)
	ListTracingJobs(c *gin.Context, params ListTracingJobsParams)

	// (POST /v1/tracing)
	CreateTracingJob(c *gin.Context)

	// (GET /v1/tracing/capabilities)
	GetTracingCapabilities(c *gin.Context)

	// (GET /v1/tracing/{request_id})
	GetTracingJob(c *gin.Context, requestID RequestID)

	// (POST /v1/tracing/{request_id}/stop)
	StopTracingJob(c *gin.Context, requestID RequestID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetOpenAPI operation middleware
func (siw *ServerInterfaceWrapper) GetOpenAPI(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetOpenAPI(c)
}

// ListProfilingJobs operation middleware
func (siw *ServerInterfaceWrapper) ListProfilingJobs(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListProfilingJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListProfilingJobs(c, params)
}

// CreateProfilingJob operation middleware
func (siw *ServerInterfaceWrapper) CreateProfilingJob(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateProfilingJob(c)
}

// GetProfilingCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetProfilingCapabilities(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfilingCapabilities(c)
}

// GetProfilingJob operation middleware
func (siw *ServerInterfaceWrapper) GetProfilingJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfilingJob(c, requestID)
}

// GetRawProfiles operation middleware
func (siw *ServerInterfaceWrapper) GetRawProfiles(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetRawProfilesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetRawProfiles(c, requestID, params)
}

// StopProfilingJob operation middleware
func (siw *ServerInterfaceWrapper) StopProfilingJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopProfilingJob(c, requestID)
}

// ListTracingJobs operation middleware
func (siw *ServerInterfaceWrapper) ListTracingJobs(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTracingJobsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", c.Request.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter limit: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", c.Request.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter offset: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTracingJobs(c, params)
}

// CreateTracingJob operation middleware
func (siw *ServerInterfaceWrapper) CreateTracingJob(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTracingJob(c)
}

// GetTracingCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetTracingCapabilities(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTracingCapabilities(c)
}

// GetTracingJob operation middleware
func (siw *ServerInterfaceWrapper) GetTracingJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTracingJob(c, requestID)
}

// StopTracingJob operation middleware
func (siw *ServerInterfaceWrapper) StopTracingJob(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "request_id" -------------
	var requestID RequestID

	err = runtime.BindStyledParameterWithOptions("simple", "request_id", c.Param("request_id"), &requestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter request_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.StopTracingJob(c, requestID)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/openapi.json", wrapper.GetOpenAPI)
	router.GET(options.BaseURL+"/v1/profiling", wrapper.ListProfilingJobs)
	router.POST(options.BaseURL+"/v1/profiling", wrapper.CreateProfilingJob)
	router.GET(options.BaseURL+"/v1/profiling/capabilities", wrapper.GetProfilingCapabilities)
	router.GET(options.BaseURL+"/v1/profiling/:request_id", wrapper.GetProfilingJob)
	router.GET(options.BaseURL+"/v1/profiling/:request_id/raw", wrapper.GetRawProfiles)
	router.POST(options.BaseURL+"/v1/profiling/:request_id/stop", wrapper.StopProfilingJob)
	router.GET(options.BaseURL+"/v1/tracing", wrapper.ListTracingJobs)
	router.POST(options.BaseURL+"/v1/tracing", wrapper.CreateTracingJob)
	router.GET(options.BaseURL+"/v1/tracing/capabilities", wrapper.GetTracingCapabilities)
	router.GET(options.BaseURL+"/v1/tracing/:request_id", wrapper.GetTracingJob)
	router.POST(options.BaseURL+"/v1/tracing/:request_id/stop", wrapper.StopTracingJob)
}

type BadRequestJSONResponse externalRef0.ErrorResponse

type ConflictJSONResponse externalRef0.ErrorResponse

type InternalErrorJSONResponse externalRef0.ErrorResponse

type NotFoundJSONResponse externalRef0.ErrorResponse

type PermissionDeniedJSONResponse externalRef0.ErrorResponse

type RequestTooLargeJSONResponse externalRef0.ErrorResponse

type ServiceUnavailableJSONResponse externalRef0.ErrorResponse

type TooManyRequestsJSONResponse externalRef0.ErrorResponse

type UnauthenticatedResponseHeaders struct {
	WWWAuthenticate string
}
type UnauthenticatedJSONResponse struct {
	Body externalRef0.ErrorResponse

	Headers UnauthenticatedResponseHeaders
}

type UnsupportedMediaTypeJSONResponse externalRef0.ErrorResponse

type GetOpenAPIRequestObject struct {
}

type GetOpenAPIResponseObject interface {
	VisitGetOpenAPIResponse(w http.ResponseWriter) error
}

type GetOpenAPI200JSONResponse map[string]interface{}

func (response GetOpenAPI200JSONResponse) VisitGetOpenAPIResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProfilingJobsRequestObject struct {
	Params ListProfilingJobsParams
}

type ListProfilingJobsResponseObject interface {
	VisitListProfilingJobsResponse(w http.ResponseWriter) error
}

type ListProfilingJobs200JSONResponse ProfilingJobListResponse

func (response ListProfilingJobs200JSONResponse) VisitListProfilingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListProfilingJobs400JSONResponse struct{ BadRequestJSONResponse }

func (response ListProfilingJobs400JSONResponse) VisitListProfilingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListProfilingJobs401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response ListProfilingJobs401JSONResponse) VisitListProfilingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListProfilingJobs403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response ListProfilingJobs403JSONResponse) VisitListProfilingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListProfilingJobs500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListProfilingJobs500JSONResponse) VisitListProfilingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJobRequestObject struct {
	Body *CreateProfilingJobJSONRequestBody
}

type CreateProfilingJobResponseObject interface {
	VisitCreateProfilingJobResponse(w http.ResponseWriter) error
}

type CreateProfilingJob201ResponseHeaders struct {
	Location string
}

type CreateProfilingJob201JSONResponse struct {
	Body    ProfilingJobResponse
	Headers CreateProfilingJob201ResponseHeaders
}

func (response CreateProfilingJob201JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateProfilingJob400JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response CreateProfilingJob401JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response CreateProfilingJob403JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob413JSONResponse struct{ RequestTooLargeJSONResponse }

func (response CreateProfilingJob413JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateProfilingJob415JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateProfilingJob429JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateProfilingJob500JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProfilingJob503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CreateProfilingJob503JSONResponse) VisitCreateProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingCapabilitiesRequestObject struct {
}

type GetProfilingCapabilitiesResponseObject interface {
	VisitGetProfilingCapabilitiesResponse(w http.ResponseWriter) error
}

type GetProfilingCapabilities200JSONResponse ProfilingCapabilitiesResponse

func (response GetProfilingCapabilities200JSONResponse) VisitGetProfilingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingCapabilities401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetProfilingCapabilities401JSONResponse) VisitGetProfilingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingCapabilities403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response GetProfilingCapabilities403JSONResponse) VisitGetProfilingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingCapabilities500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetProfilingCapabilities500JSONResponse) VisitGetProfilingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingJobRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type GetProfilingJobResponseObject interface {
	VisitGetProfilingJobResponse(w http.ResponseWriter) error
}

type GetProfilingJob200JSONResponse ProfilingJobResponse

func (response GetProfilingJob200JSONResponse) VisitGetProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingJob401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetProfilingJob401JSONResponse) VisitGetProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingJob403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response GetProfilingJob403JSONResponse) VisitGetProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingJob404JSONResponse struct{ NotFoundJSONResponse }

func (response GetProfilingJob404JSONResponse) VisitGetProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetProfilingJob500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetProfilingJob500JSONResponse) VisitGetProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfilesRequestObject struct {
	RequestID RequestID `json:"request_id"`
	Params    GetRawProfilesParams
}

type GetRawProfilesResponseObject interface {
	VisitGetRawProfilesResponse(w http.ResponseWriter) error
}

type GetRawProfiles200JSONResponse RawProfilePageResponse

func (response GetRawProfiles200JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles400JSONResponse struct{ BadRequestJSONResponse }

func (response GetRawProfiles400JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetRawProfiles401JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response GetRawProfiles403JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles404JSONResponse struct{ NotFoundJSONResponse }

func (response GetRawProfiles404JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles409JSONResponse struct{ ConflictJSONResponse }

func (response GetRawProfiles409JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetRawProfiles500JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetRawProfiles503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response GetRawProfiles503JSONResponse) VisitGetRawProfilesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingJobRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type StopProfilingJobResponseObject interface {
	VisitStopProfilingJobResponse(w http.ResponseWriter) error
}

type StopProfilingJob200JSONResponse ProfilingJobResponse

func (response StopProfilingJob200JSONResponse) VisitStopProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingJob401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StopProfilingJob401JSONResponse) VisitStopProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingJob403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response StopProfilingJob403JSONResponse) VisitStopProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingJob404JSONResponse struct{ NotFoundJSONResponse }

func (response StopProfilingJob404JSONResponse) VisitStopProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingJob409JSONResponse struct{ ConflictJSONResponse }

func (response StopProfilingJob409JSONResponse) VisitStopProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopProfilingJob500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopProfilingJob500JSONResponse) VisitStopProfilingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListTracingJobsRequestObject struct {
	Params ListTracingJobsParams
}

type ListTracingJobsResponseObject interface {
	VisitListTracingJobsResponse(w http.ResponseWriter) error
}

type ListTracingJobs200JSONResponse TracingJobListResponse

func (response ListTracingJobs200JSONResponse) VisitListTracingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTracingJobs400JSONResponse struct{ BadRequestJSONResponse }

func (response ListTracingJobs400JSONResponse) VisitListTracingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListTracingJobs401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response ListTracingJobs401JSONResponse) VisitListTracingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListTracingJobs403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response ListTracingJobs403JSONResponse) VisitListTracingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ListTracingJobs500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTracingJobs500JSONResponse) VisitListTracingJobsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJobRequestObject struct {
	Body *CreateTracingJobJSONRequestBody
}

type CreateTracingJobResponseObject interface {
	VisitCreateTracingJobResponse(w http.ResponseWriter) error
}

type CreateTracingJob201ResponseHeaders struct {
	Location string
}

type CreateTracingJob201JSONResponse struct {
	Body    TracingJobResponse
	Headers CreateTracingJob201ResponseHeaders
}

func (response CreateTracingJob201JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Location", fmt.Sprint(response.Headers.Location))
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTracingJob400JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response CreateTracingJob401JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response CreateTracingJob403JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob413JSONResponse struct{ RequestTooLargeJSONResponse }

func (response CreateTracingJob413JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(413)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob415JSONResponse struct {
	UnsupportedMediaTypeJSONResponse
}

func (response CreateTracingJob415JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(415)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response CreateTracingJob429JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTracingJob500JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTracingJob503JSONResponse struct{ ServiceUnavailableJSONResponse }

func (response CreateTracingJob503JSONResponse) VisitCreateTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingCapabilitiesRequestObject struct {
}

type GetTracingCapabilitiesResponseObject interface {
	VisitGetTracingCapabilitiesResponse(w http.ResponseWriter) error
}

type GetTracingCapabilities200JSONResponse TracingCapabilitiesResponse

func (response GetTracingCapabilities200JSONResponse) VisitGetTracingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingCapabilities401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetTracingCapabilities401JSONResponse) VisitGetTracingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingCapabilities403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response GetTracingCapabilities403JSONResponse) VisitGetTracingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingCapabilities500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetTracingCapabilities500JSONResponse) VisitGetTracingCapabilitiesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingJobRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type GetTracingJobResponseObject interface {
	VisitGetTracingJobResponse(w http.ResponseWriter) error
}

type GetTracingJob200JSONResponse TracingJobResponse

func (response GetTracingJob200JSONResponse) VisitGetTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingJob401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response GetTracingJob401JSONResponse) VisitGetTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingJob403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response GetTracingJob403JSONResponse) VisitGetTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingJob404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTracingJob404JSONResponse) VisitGetTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTracingJob500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetTracingJob500JSONResponse) VisitGetTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingJobRequestObject struct {
	RequestID RequestID `json:"request_id"`
}

type StopTracingJobResponseObject interface {
	VisitStopTracingJobResponse(w http.ResponseWriter) error
}

type StopTracingJob200JSONResponse TracingJobResponse

func (response StopTracingJob200JSONResponse) VisitStopTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingJob401JSONResponse struct{ UnauthenticatedJSONResponse }

func (response StopTracingJob401JSONResponse) VisitStopTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("WWW-Authenticate", fmt.Sprint(response.Headers.WWWAuthenticate))
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingJob403JSONResponse struct{ PermissionDeniedJSONResponse }

func (response StopTracingJob403JSONResponse) VisitStopTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingJob404JSONResponse struct{ NotFoundJSONResponse }

func (response StopTracingJob404JSONResponse) VisitStopTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingJob409JSONResponse struct{ ConflictJSONResponse }

func (response StopTracingJob409JSONResponse) VisitStopTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopTracingJob500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopTracingJob500JSONResponse) VisitStopTracingJobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Return the bundled Apiserver OpenAPI document.
	// (GET /openapi.json)
	GetOpenAPI(ctx context.Context, request GetOpenAPIRequestObject) (GetOpenAPIResponseObject, error)

	// (GET /v1/profiling)
	ListProfilingJobs(ctx context.Context, request ListProfilingJobsRequestObject) (ListProfilingJobsResponseObject, error)

	// (POST /v1/profiling)
	CreateProfilingJob(ctx context.Context, request CreateProfilingJobRequestObject) (CreateProfilingJobResponseObject, error)

	// (GET /v1/profiling/capabilities)
	GetProfilingCapabilities(ctx context.Context, request GetProfilingCapabilitiesRequestObject) (GetProfilingCapabilitiesResponseObject, error)

	// (GET /v1/profiling/{request_id})
	GetProfilingJob(ctx context.Context, request GetProfilingJobRequestObject) (GetProfilingJobResponseObject, error)

	// (GET /v1/profiling/{request_id}/raw)
	GetRawProfiles(ctx context.Context, request GetRawProfilesRequestObject) (GetRawProfilesResponseObject, error)

	// (POST /v1/profiling/{request_id}/stop)
	StopProfilingJob(ctx context.Context, request StopProfilingJobRequestObject) (StopProfilingJobResponseObject, error)

	// (GET /v1/tracing)
	ListTracingJobs(ctx context.Context, request ListTracingJobsRequestObject) (ListTracingJobsResponseObject, error)

	// (POST /v1/tracing)
	CreateTracingJob(ctx context.Context, request CreateTracingJobRequestObject) (CreateTracingJobResponseObject, error)

	// (GET /v1/tracing/capabilities)
	GetTracingCapabilities(ctx context.Context, request GetTracingCapabilitiesRequestObject) (GetTracingCapabilitiesResponseObject, error)

	// (GET /v1/tracing/{request_id})
	GetTracingJob(ctx context.Context, request GetTracingJobRequestObject) (GetTracingJobResponseObject, error)

	// (POST /v1/tracing/{request_id}/stop)
	StopTracingJob(ctx context.Context, request StopTracingJobRequestObject) (StopTracingJobResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// GetOpenAPI operation middleware
func (sh *strictHandler) GetOpenAPI(ctx *gin.Context) {
	var request GetOpenAPIRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPI(ctx, request.(GetOpenAPIRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPI")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetOpenAPIResponseObject); ok {
		if err := validResponse.VisitGetOpenAPIResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListProfilingJobs operation middleware
func (sh *strictHandler) ListProfilingJobs(ctx *gin.Context, params ListProfilingJobsParams) {
	var request ListProfilingJobsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListProfilingJobs(ctx, request.(ListProfilingJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListProfilingJobs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListProfilingJobsResponseObject); ok {
		if err := validResponse.VisitListProfilingJobsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProfilingJob operation middleware
func (sh *strictHandler) CreateProfilingJob(ctx *gin.Context) {
	var request CreateProfilingJobRequestObject

	var body CreateProfilingJobJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProfilingJob(ctx, request.(CreateProfilingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProfilingJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateProfilingJobResponseObject); ok {
		if err := validResponse.VisitCreateProfilingJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfilingCapabilities operation middleware
func (sh *strictHandler) GetProfilingCapabilities(ctx *gin.Context) {
	var request GetProfilingCapabilitiesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfilingCapabilities(ctx, request.(GetProfilingCapabilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfilingCapabilities")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProfilingCapabilitiesResponseObject); ok {
		if err := validResponse.VisitGetProfilingCapabilitiesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProfilingJob operation middleware
func (sh *strictHandler) GetProfilingJob(ctx *gin.Context, requestID RequestID) {
	var request GetProfilingJobRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetProfilingJob(ctx, request.(GetProfilingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProfilingJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetProfilingJobResponseObject); ok {
		if err := validResponse.VisitGetProfilingJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRawProfiles operation middleware
func (sh *strictHandler) GetRawProfiles(ctx *gin.Context, requestID RequestID, params GetRawProfilesParams) {
	var request GetRawProfilesRequestObject

	request.RequestID = requestID
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetRawProfiles(ctx, request.(GetRawProfilesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRawProfiles")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetRawProfilesResponseObject); ok {
		if err := validResponse.VisitGetRawProfilesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopProfilingJob operation middleware
func (sh *strictHandler) StopProfilingJob(ctx *gin.Context, requestID RequestID) {
	var request StopProfilingJobRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StopProfilingJob(ctx, request.(StopProfilingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopProfilingJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StopProfilingJobResponseObject); ok {
		if err := validResponse.VisitStopProfilingJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTracingJobs operation middleware
func (sh *strictHandler) ListTracingJobs(ctx *gin.Context, params ListTracingJobsParams) {
	var request ListTracingJobsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTracingJobs(ctx, request.(ListTracingJobsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTracingJobs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ListTracingJobsResponseObject); ok {
		if err := validResponse.VisitListTracingJobsResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTracingJob operation middleware
func (sh *strictHandler) CreateTracingJob(ctx *gin.Context) {
	var request CreateTracingJobRequestObject

	var body CreateTracingJobJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTracingJob(ctx, request.(CreateTracingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTracingJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateTracingJobResponseObject); ok {
		if err := validResponse.VisitCreateTracingJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTracingCapabilities operation middleware
func (sh *strictHandler) GetTracingCapabilities(ctx *gin.Context) {
	var request GetTracingCapabilitiesRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTracingCapabilities(ctx, request.(GetTracingCapabilitiesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTracingCapabilities")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetTracingCapabilitiesResponseObject); ok {
		if err := validResponse.VisitGetTracingCapabilitiesResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTracingJob operation middleware
func (sh *strictHandler) GetTracingJob(ctx *gin.Context, requestID RequestID) {
	var request GetTracingJobRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTracingJob(ctx, request.(GetTracingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTracingJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetTracingJobResponseObject); ok {
		if err := validResponse.VisitGetTracingJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopTracingJob operation middleware
func (sh *strictHandler) StopTracingJob(ctx *gin.Context, requestID RequestID) {
	var request StopTracingJobRequestObject

	request.RequestID = requestID

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StopTracingJob(ctx, request.(StopTracingJobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopTracingJob")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(StopTracingJobResponseObject); ok {
		if err := validResponse.VisitStopTracingJobResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
