// Copyright 2026 The HuaTuo Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package server provides primitives to interact with the OpenAPI HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.2. DO NOT EDIT.
package server

import (
	"time"

	externalRef0 "huatuo-bamai/apis/v1"
)

const (
	BearerAuthScopes bearerAuthContextKey = "BearerAuth.Scopes"
)

// Defines values for JobStatus.
const (
	JobStatusCompleted      JobStatus = "completed"
	JobStatusFailed         JobStatus = "failed"
	JobStatusOutcomeUnknown JobStatus = "outcome_unknown"
	JobStatusPending        JobStatus = "pending"
	JobStatusRunning        JobStatus = "running"
	JobStatusStopped        JobStatus = "stopped"
	JobStatusStopping       JobStatus = "stopping"
)

// Valid indicates whether the value is a known member of the JobStatus enum.
func (e JobStatus) Valid() bool {
	switch e {
	case JobStatusCompleted:
		return true
	case JobStatusFailed:
		return true
	case JobStatusOutcomeUnknown:
		return true
	case JobStatusPending:
		return true
	case JobStatusRunning:
		return true
	case JobStatusStopped:
		return true
	case JobStatusStopping:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingLanguage.
const (
	ProfilingLanguageC      ProfilingLanguage = "c"
	ProfilingLanguageCPP    ProfilingLanguage = "c++"
	ProfilingLanguageGo     ProfilingLanguage = "go"
	ProfilingLanguageJava   ProfilingLanguage = "java"
	ProfilingLanguagePython ProfilingLanguage = "python"
)

// Valid indicates whether the value is a known member of the ProfilingLanguage enum.
func (e ProfilingLanguage) Valid() bool {
	switch e {
	case ProfilingLanguageC:
		return true
	case ProfilingLanguageCPP:
		return true
	case ProfilingLanguageGo:
		return true
	case ProfilingLanguageJava:
		return true
	case ProfilingLanguagePython:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingMode.
const (
	ProfilingModeObjectAlloc   ProfilingMode = "object_alloc"
	ProfilingModeObjectUsage   ProfilingMode = "object_usage"
	ProfilingModeOffCPU        ProfilingMode = "offcpu"
	ProfilingModeOnCPU         ProfilingMode = "oncpu"
	ProfilingModePhysicalAlloc ProfilingMode = "physical_alloc"
	ProfilingModePhysicalUsage ProfilingMode = "physical_usage"
	ProfilingModeVirtualAlloc  ProfilingMode = "virtual_alloc"
)

// Valid indicates whether the value is a known member of the ProfilingMode enum.
func (e ProfilingMode) Valid() bool {
	switch e {
	case ProfilingModeObjectAlloc:
		return true
	case ProfilingModeObjectUsage:
		return true
	case ProfilingModeOffCPU:
		return true
	case ProfilingModeOnCPU:
		return true
	case ProfilingModePhysicalAlloc:
		return true
	case ProfilingModePhysicalUsage:
		return true
	case ProfilingModeVirtualAlloc:
		return true
	default:
		return false
	}
}

// Defines values for ProfilingType.
const (
	ProfilingTypeCPU    ProfilingType = "cpu"
	ProfilingTypeMemory ProfilingType = "memory"
)

// Valid indicates whether the value is a known member of the ProfilingType enum.
func (e ProfilingType) Valid() bool {
	switch e {
	case ProfilingTypeCPU:
		return true
	case ProfilingTypeMemory:
		return true
	default:
		return false
	}
}

// Defines values for TracingType.
const (
	TracingTypeIO             TracingType = "io_tracing"
	TracingTypeNetworkingDrop TracingType = "networking_drop"
	TracingTypeTCPRetransmit  TracingType = "tcp_retransmit"
)

// Valid indicates whether the value is a known member of the TracingType enum.
func (e TracingType) Valid() bool {
	switch e {
	case TracingTypeIO:
		return true
	case TracingTypeNetworkingDrop:
		return true
	case TracingTypeTCPRetransmit:
		return true
	default:
		return false
	}
}

// CreateProfilingJobRequest defines model for CreateProfilingJobRequest.
type CreateProfilingJobRequest struct {
	BinaryMatchPath *string           `json:"binary_match_path,omitempty"`
	ContainerID     *string           `json:"container_id,omitempty"`
	DurationSeconds int64             `json:"duration_seconds"`
	Hostname        string            `json:"hostname"`
	Language        ProfilingLanguage `json:"language"`
	Mode            ProfilingMode     `json:"mode"`

	// Scope Boundary observed by an on-demand operation.
	Scope externalRef0.ObservationScope `json:"scope"`
	Type  ProfilingType                 `json:"type"`
}

// CreateTracingJobRequest defines model for CreateTracingJobRequest.
type CreateTracingJobRequest struct {
	ContainerID     *string `json:"container_id,omitempty"`
	DurationSeconds int64   `json:"duration_seconds"`
	Hostname        string  `json:"hostname"`

	// Scope Boundary observed by an on-demand operation.
	Scope externalRef0.ObservationScope `json:"scope"`
	Type  TracingType                   `json:"type"`
}

// Job defines model for Job.
type Job struct {
	ContainerID     *string     `json:"container_id,omitempty"`
	CreatedAt       time.Time   `json:"created_at"`
	DurationSeconds int64       `json:"duration_seconds"`
	EndedAt         *time.Time  `json:"ended_at,omitempty"`
	Failure         *JobFailure `json:"failure,omitempty"`
	Hostname        string      `json:"hostname"`
	RequestID       string      `json:"request_id"`
	ResultURL       *string     `json:"result_url,omitempty"`

	// Scope Boundary observed by an on-demand operation.
	Scope     externalRef0.ObservationScope `json:"scope"`
	StartedAt *time.Time                    `json:"started_at,omitempty"`
	Status    JobStatus                     `json:"status"`
	UpdatedAt time.Time                     `json:"updated_at"`
}

// JobFailure defines model for JobFailure.
type JobFailure struct {
	// Code Stable machine-readable error code.
	Code    externalRef0.ErrorCode `json:"code"`
	Message string                 `json:"message"`
}

// JobStatus defines model for JobStatus.
type JobStatus string

// ProfilingCapabilities defines model for ProfilingCapabilities.
type ProfilingCapabilities struct {
	Items []ProfilingCapability `json:"items"`
}

// ProfilingCapabilitiesResponse defines model for ProfilingCapabilitiesResponse.
type ProfilingCapabilitiesResponse struct {
	Data ProfilingCapabilities `json:"data"`
}

// ProfilingCapability defines model for ProfilingCapability.
type ProfilingCapability struct {
	Language            ProfilingLanguage               `json:"language"`
	Modes               []ProfilingMode                 `json:"modes"`
	SupportedScopes     []externalRef0.ObservationScope `json:"supported_scopes"`
	SupportsBinaryMatch bool                            `json:"supports_binary_match"`
	Type                ProfilingType                   `json:"type"`
}

// ProfilingJob defines model for ProfilingJob.
type ProfilingJob struct {
	BinaryMatchPath *string           `json:"binary_match_path,omitempty"`
	ContainerID     *string           `json:"container_id,omitempty"`
	CreatedAt       time.Time         `json:"created_at"`
	DurationSeconds int64             `json:"duration_seconds"`
	EndedAt         *time.Time        `json:"ended_at,omitempty"`
	Failure         *JobFailure       `json:"failure,omitempty"`
	Hostname        string            `json:"hostname"`
	Language        ProfilingLanguage `json:"language"`
	Mode            ProfilingMode     `json:"mode"`
	RequestID       string            `json:"request_id"`
	ResultURL       *string           `json:"result_url,omitempty"`

	// Scope Boundary observed by an on-demand operation.
	Scope     externalRef0.ObservationScope `json:"scope"`
	StartedAt *time.Time                    `json:"started_at,omitempty"`
	Status    JobStatus                     `json:"status"`
	Type      ProfilingType                 `json:"type"`
	UpdatedAt time.Time                     `json:"updated_at"`
}

// ProfilingJobListResponse defines model for ProfilingJobListResponse.
type ProfilingJobListResponse struct {
	Data struct {
		Items  []ProfilingJob `json:"items"`
		Limit  int            `json:"limit"`
		Offset int            `json:"offset"`
		Total  int            `json:"total"`
	} `json:"data"`
}

// ProfilingJobResponse defines model for ProfilingJobResponse.
type ProfilingJobResponse struct {
	Data ProfilingJob `json:"data"`
}

// ProfilingLanguage defines model for ProfilingLanguage.
type ProfilingLanguage string

// ProfilingMode defines model for ProfilingMode.
type ProfilingMode string

// ProfilingType defines model for ProfilingType.
type ProfilingType string

// RawProfile defines model for RawProfile.
type RawProfile struct {
	CapturedAt        time.Time   `json:"captured_at"`
	ContainerHostname *string     `json:"container_hostname,omitempty"`
	ContainerID       *string     `json:"container_id,omitempty"`
	ContainerQos      *string     `json:"container_qos,omitempty"`
	ContainerType     *string     `json:"container_type,omitempty"`
	Hostname          string      `json:"hostname"`
	Profile           interface{} `json:"profile"`
	ProfileType       string      `json:"profile_type"`
	Region            string      `json:"region"`
	UploadedAt        time.Time   `json:"uploaded_at"`
}

// RawProfilePage defines model for RawProfilePage.
type RawProfilePage struct {
	HasMore bool         `json:"has_more"`
	Items   []RawProfile `json:"items"`
	Limit   int          `json:"limit"`
	Offset  int          `json:"offset"`
}

// RawProfilePageResponse defines model for RawProfilePageResponse.
type RawProfilePageResponse struct {
	Data RawProfilePage `json:"data"`
}

// TracingCapabilities defines model for TracingCapabilities.
type TracingCapabilities struct {
	Items []TracingCapability `json:"items"`
}

// TracingCapabilitiesResponse defines model for TracingCapabilitiesResponse.
type TracingCapabilitiesResponse struct {
	Data TracingCapabilities `json:"data"`
}

// TracingCapability defines model for TracingCapability.
type TracingCapability struct {
	SupportedScopes []externalRef0.ObservationScope `json:"supported_scopes"`
	Type            TracingType                     `json:"type"`
}

// TracingJob defines model for TracingJob.
type TracingJob struct {
	ContainerID     *string     `json:"container_id,omitempty"`
	CreatedAt       time.Time   `json:"created_at"`
	DurationSeconds int64       `json:"duration_seconds"`
	EndedAt         *time.Time  `json:"ended_at,omitempty"`
	Failure         *JobFailure `json:"failure,omitempty"`
	Hostname        string      `json:"hostname"`
	RequestID       string      `json:"request_id"`
	ResultURL       *string     `json:"result_url,omitempty"`

	// Scope Boundary observed by an on-demand operation.
	Scope     externalRef0.ObservationScope `json:"scope"`
	StartedAt *time.Time                    `json:"started_at,omitempty"`
	Status    JobStatus                     `json:"status"`
	Type      TracingType                   `json:"type"`
	UpdatedAt time.Time                     `json:"updated_at"`
}

// TracingJobListResponse defines model for TracingJobListResponse.
type TracingJobListResponse struct {
	Data struct {
		Items  []TracingJob `json:"items"`
		Limit  int          `json:"limit"`
		Offset int          `json:"offset"`
		Total  int          `json:"total"`
	} `json:"data"`
}

// TracingJobResponse defines model for TracingJobResponse.
type TracingJobResponse struct {
	Data TracingJob `json:"data"`
}

// TracingType defines model for TracingType.
type TracingType string

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// RequestID defines model for RequestID.
type RequestID = string

// BadRequest defines model for BadRequest.
type BadRequest = externalRef0.ErrorResponse

// Conflict defines model for Conflict.
type Conflict = externalRef0.ErrorResponse

// InternalError defines model for InternalError.
type InternalError = externalRef0.ErrorResponse

// NotFound defines model for NotFound.
type NotFound = externalRef0.ErrorResponse

// PermissionDenied defines model for PermissionDenied.
type PermissionDenied = externalRef0.ErrorResponse

// RequestTooLarge defines model for RequestTooLarge.
type RequestTooLarge = externalRef0.ErrorResponse

// ServiceUnavailable defines model for ServiceUnavailable.
type ServiceUnavailable = externalRef0.ErrorResponse

// TooManyRequests defines model for TooManyRequests.
type TooManyRequests = externalRef0.ErrorResponse

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = externalRef0.ErrorResponse

// UnsupportedMediaType defines model for UnsupportedMediaType.
type UnsupportedMediaType = externalRef0.ErrorResponse

// bearerAuthContextKey is the context key for BearerAuth security scheme
type bearerAuthContextKey string

// ListProfilingJobsParams defines parameters for ListProfilingJobs.
type ListProfilingJobsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetRawProfilesParams defines parameters for GetRawProfiles.
type GetRawProfilesParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListTracingJobsParams defines parameters for ListTracingJobs.
type ListTracingJobsParams struct {
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateProfilingJobJSONRequestBody defines body for CreateProfilingJob for application/json ContentType.
type CreateProfilingJobJSONRequestBody = CreateProfilingJobRequest

// CreateTracingJobJSONRequestBody defines body for CreateTracingJob for application/json ContentType.
type CreateTracingJobJSONRequestBody = CreateTracingJobRequest
